"""init

Revision ID: 8caa39b31f3b
Revises: 
Create Date: 2026-06-27 23:18:42.367241
"""
from alembic import op
import sqlalchemy as sa


revision = '8caa39b31f3b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_email', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity', sa.String(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('changes', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('routing_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('point', sa.String(), nullable=True),
    sa.Column('link_type', sa.String(), nullable=True),
    sa.Column('parent', sa.String(), nullable=True),
    sa.Column('vlan', sa.String(), nullable=True),
    sa.Column('ip_gateway', sa.String(), nullable=True),
    sa.Column('ip_master', sa.String(), nullable=True),
    sa.Column('user_master', sa.String(), nullable=True),
    sa.Column('pass_master', sa.String(), nullable=True),
    sa.Column('ip_slave', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscribers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(), nullable=True),
    sa.Column('customer', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('exp_date', sa.String(), nullable=True),
    sa.Column('wakil', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('tag', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('rule_field', sa.String(), nullable=True),
    sa.Column('rule_value', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('towers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('agent', sa.String(), nullable=True),
    sa.Column('agency_id', sa.String(), nullable=True),
    sa.Column('reseller', sa.String(), nullable=True),
    sa.Column('affiliate', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('link_type', sa.String(), nullable=True),
    sa.Column('switch_type', sa.String(), nullable=True),
    sa.Column('user_count', sa.String(), nullable=True),
    sa.Column('vlan', sa.String(), nullable=True),
    sa.Column('admin_page', sa.String(), nullable=True),
    sa.Column('admin_pass', sa.String(), nullable=True),
    sa.Column('area', sa.String(), nullable=True),
    sa.Column('gps_lat', sa.String(), nullable=True),
    sa.Column('gps_lng', sa.String(), nullable=True),
    sa.Column('height', sa.String(), nullable=True),
    sa.Column('parent_name', sa.String(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('port', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['towers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_towers_area'), 'towers', ['area'], unique=False)
    op.create_index(op.f('ix_towers_name'), 'towers', ['name'], unique=False)
    op.create_index(op.f('ix_towers_reseller'), 'towers', ['reseller'], unique=False)
    op.create_index(op.f('ix_towers_status'), 'towers', ['status'], unique=False)
    op.create_index(op.f('ix_towers_zone_id'), 'towers', ['zone_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('backbone_feeds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('switch_name', sa.String(), nullable=True),
    sa.Column('switch_ip', sa.String(), nullable=True),
    sa.Column('port', sa.String(), nullable=True),
    sa.Column('feeds_name', sa.String(), nullable=True),
    sa.Column('feeds_tower_id', sa.Integer(), nullable=True),
    sa.Column('ssid', sa.String(), nullable=True),
    sa.Column('vlan', sa.String(), nullable=True),
    sa.Column('ip', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['feeds_tower_id'], ['towers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ip_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('point', sa.String(), nullable=True),
    sa.Column('tower_ref', sa.String(), nullable=True),
    sa.Column('tower_id', sa.Integer(), nullable=True),
    sa.Column('link_type', sa.String(), nullable=True),
    sa.Column('parent', sa.String(), nullable=True),
    sa.Column('vlan', sa.String(), nullable=True),
    sa.Column('ip_block', sa.String(), nullable=True),
    sa.Column('ip_master', sa.String(), nullable=True),
    sa.Column('user_master', sa.String(), nullable=True),
    sa.Column('pass_master', sa.String(), nullable=True),
    sa.Column('ip_slave', sa.String(), nullable=True),
    sa.Column('user_slave', sa.String(), nullable=True),
    sa.Column('pass_slave', sa.String(), nullable=True),
    sa.Column('sw_ip', sa.String(), nullable=True),
    sa.Column('sw_pass', sa.String(), nullable=True),
    sa.Column('rs_pass', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['tower_id'], ['towers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('links',
    sa.Column('tower_id', sa.Integer(), nullable=False),
    sa.Column('ssid', sa.String(), nullable=True),
    sa.Column('device_name', sa.String(), nullable=True),
    sa.Column('device_type', sa.String(), nullable=True),
    sa.Column('wireless_pass', sa.String(), nullable=True),
    sa.Column('unlock_code', sa.String(), nullable=True),
    sa.Column('serial_number', sa.String(), nullable=True),
    sa.Column('mac_address', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('ip', sa.String(), nullable=True),
    sa.Column('gateway', sa.String(), nullable=True),
    sa.Column('subnet', sa.String(), nullable=True),
    sa.Column('vlan', sa.String(), nullable=True),
    sa.Column('port', sa.String(), nullable=True),
    sa.Column('target', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flags', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tower_id'], ['towers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_links_tower_id'), 'links', ['tower_id'], unique=False)
    op.create_table('sectors',
    sa.Column('tower_id', sa.Integer(), nullable=False),
    sa.Column('ssid', sa.String(), nullable=True),
    sa.Column('device_name', sa.String(), nullable=True),
    sa.Column('device_type', sa.String(), nullable=True),
    sa.Column('wireless_pass', sa.String(), nullable=True),
    sa.Column('serial_number', sa.String(), nullable=True),
    sa.Column('mac_address', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('ip', sa.String(), nullable=True),
    sa.Column('gateway', sa.String(), nullable=True),
    sa.Column('subnet', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flags', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tower_id'], ['towers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sectors_tower_id'), 'sectors', ['tower_id'], unique=False)
    op.create_table('servers',
    sa.Column('tower_id', sa.Integer(), nullable=False),
    sa.Column('device_name', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flags', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tower_id'], ['towers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_servers_tower_id'), 'servers', ['tower_id'], unique=False)
    op.create_table('switches',
    sa.Column('tower_id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('gateway', sa.String(), nullable=True),
    sa.Column('subnet', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flags', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tower_id'], ['towers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_switches_tower_id'), 'switches', ['tower_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_switches_tower_id'), table_name='switches')
    op.drop_table('switches')
    op.drop_index(op.f('ix_servers_tower_id'), table_name='servers')
    op.drop_table('servers')
    op.drop_index(op.f('ix_sectors_tower_id'), table_name='sectors')
    op.drop_table('sectors')
    op.drop_index(op.f('ix_links_tower_id'), table_name='links')
    op.drop_table('links')
    op.drop_table('ip_allocations')
    op.drop_table('backbone_feeds')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_towers_zone_id'), table_name='towers')
    op.drop_index(op.f('ix_towers_status'), table_name='towers')
    op.drop_index(op.f('ix_towers_reseller'), table_name='towers')
    op.drop_index(op.f('ix_towers_name'), table_name='towers')
    op.drop_index(op.f('ix_towers_area'), table_name='towers')
    op.drop_table('towers')
    op.drop_table('zones')
    op.drop_table('subscribers')
    op.drop_table('routing_points')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
